//auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_CLOSE = 'LOGIN_CLOSE';
export const AUTENTICATE_USER = 'AUTENTICATE_USER';
export const AUTENTICATE_USER_ERROR = 'AUTENTICATE_USER_ERROR';
export const SET_INFO_PERMISSION = 'SET_INFO_PERMISSION';
export const SET_INFO_PERMISSION_ERROR = 'SET_INFO_PERMISSION_ERROR';
export const SET_AUTORIZATE = 'SET_AUTORIZATE';
export const SET_SOCKECT = 'SET_SOCKECT';
export const CLEAR_ALERT = 'CLEAR_ALERT';


